// The mascot's body. 32 by 32 grid. Rows 3 to 28, columns 3 to 28.
// O outline, B body (the current hue), H highlight, S shade, . transparent.
// Feature zones (column, row): brows rows 7 to 10, eyes rows 11 to 16 (left 9 to 13,
// right 18 to 22), mouth rows 19 to 23 columns 10 to 21.
export const BODY = {
  x: 0,
  y: 0,
  rows: [
    '................................',
    '................................',
    '................................',
    '..........OOOOOOOOOOOO..........',
    '........OOBBBBBBBBBBBBOO........',
    '.......OBBHHBBBBBBBBBBBBO.......',
    '......OBBHBBBBBBBBBBBBBBBO......',
    '.....OBBHBBBBBBBBBBBBBBBBBO.....',
    '....OBBBBBBBBBBBBBBBBBBBBBBO....',
    '....OBBBBBBBBBBBBBBBBBBBBBBO....',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '...OBBBBBBBBBBBBBBBBBBBBBBBBO...',
    '....OBBBBBBBBBBBBBBBBBBBBBSO....',
    '....OBBBBBBBBBBBBBBBBBBBBBSO....',
    '.....OBBBBBBBBBBBBBBBBBBSSO.....',
    '......OBBBBBBBBBBBBBBBSSSO......',
    '.......OSBBBBBBBBBBBSSSSO.......',
    '........OOSSSSSSSSSSSSOO........',
    '..........OOOOOOOOOOOO..........',
    '................................',
    '................................',
    '................................',
  ],
}
