/**
 * Prices people typed in themselves, and the only place they live.
 *
 * Until this file existed, a correction was collected and applied to nothing:
 * `app/public/js/store.js` said so in its own comment on the `corrections`
 * field, and the mascot line that goes with it ("counts once a second tag
 * agrees") described a mechanism that was not built. This table is that
 * mechanism. A correction written here is read back by
 * `spine/src/sources/corrections.ts` as an ordinary price point, so the next
 * verdict for the same product is computed with it in the comparison set.
 *
 * SEPARATE FILE, not a table inside prices.db, for the reason `store.ts` gives
 * for keeping observations out of the catalogue: these two tables have
 * different owners and different lifetimes. `observation` is written by a
 * crawler and can be rebuilt from a re-crawl. A correction cannot be rebuilt by
 * anything: it is one person's eyes on one shelf on one day, and if it is lost
 * it is lost. It gets a file nothing else rewrites.
 *
 * ONE PERSON, ONE SHOP, ONE DAY, ONE PRICE. The unique index is the whole
 * integrity story. Grocery needs two price points to produce a verdict
 * (`spine/src/categories.ts`, minPoints 2), so without that index a person who
 * taps save twice manufactures the agreement the product is supposed to wait
 * for, and the app would tell them their own number is confirmed. A repeat for
 * the same subject, shop and day overwrites: the newest reading of the same tag
 * is a correction of the earlier one, never a second witness to it.
 *
 * WHAT IS NOT HERE. No name, no email, no account, no location. `device_id` is
 * the random UUID the client generates on first run (`app/public/js/device.js`)
 * and it identifies a phone's local storage, never a person, exactly as
 * `app/src/scans.ts` documents for the same field. `seller` is what the person
 * typed, because a price with no shop cannot be excluded from its own
 * comparison later, and the spine's self-exclusion keys on that string.
 *
 * NEVER THROWS. Same contract as `app/src/scans.ts`: a store that could not be
 * opened is a `db: null` handle whose writes are counted in `dropped`, not an
 * exception thrown at a request handler. A phone correcting a price must never
 * be able to take the server down.
 */

import { DatabaseSync } from 'node:sqlite';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Resolved once and exported, the same way `store.ts` exports `PRICES_DB_PATH`,
 * so the writer (`app/server.ts`) and the reader (the spine source) agree on
 * where the file is without either hardcoding a path into the other's package.
 */
export const CORRECTIONS_DB_PATH =
  process.env.SHIN_CORRECTIONS ?? fileURLToPath(new URL('../data/corrections.db', import.meta.url));

/**
 * Whether the number is what the thing normally costs or what it costs today.
 * The same two values `price/src/store.ts` uses, and the reason the correction
 * screen asks at all: `spine/src/contract.ts` calls collapsing these "the single
 * most expensive mistake available here", and a shopper reading a sale tag into
 * a field labelled regular walks the everyday price down for everyone.
 */
export type CorrectionKind = 'regular' | 'promotional';

export interface CorrectionInput {
  /**
   * Generated by the client, unique per correction, and the reason a phone with
   * no signal can retry safely. The queue in `app/public/js/store.js` re-sends
   * anything it has not seen an acknowledgement for, and without this a flaky
   * aisle turns one price into three witnesses.
   */
  readonly clientId: string;
  readonly deviceId: string;
  /** Barcode, zero padded to 13 by `recordCorrection`. Null when the scan produced none. */
  readonly code: string | null;
  /** The spine's own identity key, when a verdict had one. Null on a refusal with no identity. */
  readonly productId: string | null;
  /** What was on screen when they corrected it. Display only, never a join key. */
  readonly label: string | null;
  readonly category: string | null;
  readonly seller: string;
  readonly priceCents: number;
  readonly kind: CorrectionKind;
  /** ISO date, no time. A tag is a fact about a day. */
  readonly seenOn: string;
}

export interface CorrectionRow {
  readonly id: number;
  readonly client_id: string;
  readonly device_id: string;
  readonly subject: string;
  readonly code: string | null;
  readonly product_id: string | null;
  readonly label: string | null;
  readonly category: string | null;
  readonly seller: string;
  readonly price_cents: number;
  readonly kind: CorrectionKind;
  readonly seen_on: string;
  readonly recorded_at: string;
}

const DDL = `
CREATE TABLE IF NOT EXISTS correction (
  id          INTEGER PRIMARY KEY,
  client_id   TEXT NOT NULL UNIQUE,
  device_id   TEXT NOT NULL,
  subject     TEXT NOT NULL,
  code        TEXT,
  product_id  TEXT,
  label       TEXT,
  category    TEXT,
  seller      TEXT NOT NULL,
  seller_key  TEXT NOT NULL,
  price_cents INTEGER NOT NULL,
  kind        TEXT NOT NULL CHECK (kind IN ('regular', 'promotional')),
  seen_on     TEXT NOT NULL,
  recorded_at TEXT NOT NULL
) STRICT;

CREATE UNIQUE INDEX IF NOT EXISTS correction_one_per_shop_per_day
  ON correction(device_id, subject, seller_key, seen_on);

CREATE INDEX IF NOT EXISTS correction_subject ON correction(subject, seen_on);
CREATE INDEX IF NOT EXISTS correction_code ON correction(code);
CREATE INDEX IF NOT EXISTS correction_product ON correction(product_id);
CREATE INDEX IF NOT EXISTS correction_dedupe ON correction(device_id, seller_key, seen_on);

/*
 * The rate limit's own index, item 15c. Keyed on when the row was WRITTEN, not
 * on the day the tag was seen, because the limit is about how fast one phone
 * can file and seen_on is a field the phone chooses. Added to this DDL rather
 * than to a migration for the reason the whole block is safe to re-run: every
 * statement here is IF NOT EXISTS and the DDL is executed on every open, so a
 * database written before today gains the index the next time the app starts.
 */
CREATE INDEX IF NOT EXISTS correction_by_device_written ON correction(device_id, recorded_at);
`;

export interface CorrectionStore {
  readonly path: string;
  readonly db: DatabaseSync | null;
  /** Writes or reads that could not complete since this handle was opened. */
  dropped: number;
  /** Why the last drop happened. Empty string when nothing has dropped. */
  droppedWhy: string;
}

let active: CorrectionStore | null = null;

/** The store currently in use, or null if nothing has opened one yet. */
export function activeCorrectionStore(): CorrectionStore | null {
  return active;
}

/**
 * Opens (creating if needed) the corrections database and makes it the target
 * of future calls. Never throws: a path that cannot be created comes back as a
 * handle with `db: null` and `droppedWhy` set.
 */
export function openCorrectionStore(path: string = CORRECTIONS_DB_PATH): CorrectionStore {
  let db: DatabaseSync | null = null;
  let droppedWhy = '';
  try {
    if (path !== ':memory:') mkdirSync(dirname(path), { recursive: true });
    db = new DatabaseSync(path);
    db.exec('PRAGMA journal_mode = WAL');
    db.exec(DDL);
  } catch (err) {
    db = null;
    droppedWhy = err instanceof Error ? err.message : String(err);
  }
  const store: CorrectionStore = { path, db, dropped: 0, droppedWhy };
  active = store;
  return store;
}

function store(): CorrectionStore {
  return active ?? openCorrectionStore();
}

export function padGtin(gtin: string): string {
  return gtin.padStart(13, '0');
}

/**
 * The key a correction is filed under and looked up by, in priority order:
 * a barcode if there was one, then the spine's identity key, then the text the
 * person was looking at.
 *
 * The prefixes are not decoration. Without them a product id that happened to
 * be all digits would collide with a barcode, and a typed label would collide
 * with either, which is the quiet kind of wrong that shows a shopper someone
 * else's price for a different thing.
 */
export function subjectOf(input: {
  code: string | null;
  productId: string | null;
  label: string | null;
}): string | null {
  if (input.code && input.code.trim() !== '') return `gtin:${padGtin(input.code.trim())}`;
  if (input.productId && input.productId.trim() !== '') return `pid:${input.productId.trim()}`;
  const label = (input.label ?? '').trim().toLowerCase().replace(/\s+/g, ' ');
  return label === '' ? null : `text:${label}`;
}

/**
 * The self-exclusion key. Deliberately the same shape as
 * `spine/src/sources/source.ts`'s `normalizeSeller`, duplicated rather than
 * imported because this package must not depend on the spine (the spine already
 * depends on this direction, via the source adapter). If those two ever
 * disagree, a correction from the shop a shopper is standing in stops being
 * excluded from its own comparison, so the shared test in
 * `price/test/corrections.test.ts` asserts they agree on the cases that matter.
 */
const SELLER_NOISE = /\b(inc|ltd|ltee|limited|corp|corporation|co|canada|ca|com|banners|stores|store)\b/g;

const COMBINING_LOW = 0x0300;
const COMBINING_HIGH = 0x036f;

export function sellerKey(seller: string): string {
  // Folded by code point rather than by a literal character class, for the
  // reason source.ts gives: the rule stays readable in a diff, and a range of
  // invisible combining marks pasted into a regex is a thing nobody can review.
  let folded = '';
  for (const ch of seller.normalize('NFD')) {
    const code = ch.codePointAt(0) ?? 0;
    if (code >= COMBINING_LOW && code <= COMBINING_HIGH) continue;
    folded += ch;
  }
  const base = folded
    .toLowerCase()
    .replace(/[^a-z0-9\s.]/g, ' ')
    .replace(/\./g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  const stripped = base.replace(SELLER_NOISE, ' ').trim();
  const kept = stripped.length > 0 ? stripped : base;
  return kept.replace(/\s+/g, '');
}

/** The literal string the spine uses when no shop was named. Never a seller, so never stored as one. */
const NOT_A_SELLER = 'given';

/**
 * How many NEW typed prices one phone may file in one day. Item 15c.
 *
 * WHERE 200 COMES FROM, and it is a design default rather than a measurement.
 * The beta build plan's own target for seeding a store is "the 200 items per
 * store the six of you actually buy" (item 16c), so 200 is the largest honest
 * day anybody in this beta is expected to have: a whole afternoon walking one
 * store typing every price on the list. A limit under that would refuse the
 * exact work the beta exists to do; a limit far over it stops being a limit.
 *
 * WHAT IT IS FOR, since the unique index upstream already stops the obvious
 * abuse. That index caps one row per device per shop per subject per day, which
 * stops one person manufacturing agreement with themselves on ONE shelf. It
 * does nothing about volume across shelves, and volume is what an attack on a
 * price store looks like: a script filing a thousand rows overnight does not
 * need to file two for the same product. This is the ceiling on that.
 *
 * NOT A JUDGEMENT ABOUT THE PERSON. Hard rule 3 in this repo's CLAUDE.md points
 * the aggression at the price, the store or the brand and never at the user, so
 * the sentence below says what the app does and never what the person is.
 *
 * REVERSES IF a real day of seeding is ever measured above it. The number to
 * change is here, the reason is this comment, and the test that pins it is in
 * `price/test/reporter-limits.test.ts`.
 */
export const TYPED_PRICES_PER_DEVICE_PER_DAY = 200;

/**
 * The reporter reliability score, item 15c: "starts at zero and rises with
 * corroborated reports."
 *
 * Full at ten corroborated readings. A design default, like the cap above, and
 * chosen small on purpose: the score exists to separate a phone that
 * has been confirmed by other people from one nobody has ever confirmed, and ten
 * is about a fortnight of ordinary shopping rather than a career.
 *
 * WHAT THIS SCORE DOES TODAY: nothing gates on it, and that is deliberate rather
 * than unfinished. Every score starts at zero, including the six beta testers'
 * on the day they install; gating anything on it would refuse the first walk
 * through the first store, which is the run that produces every corroboration
 * there will ever be. It is computed, reported and stored nowhere else so that
 * the day there IS volume, the calibration question can be asked against real
 * numbers instead of against a rule somebody wrote first.
 *
 * WHAT IT IS NOT: a measure of honesty. It counts readings other people's phones
 * agreed with. A person who only ever shops somewhere nobody else in the beta
 * shops scores zero and has done nothing wrong, which is the main reason it must
 * not gate anything yet.
 */
export const RELIABILITY_FULL_AT = 10;

export type RecordResult =
  | {
      readonly ok: true;
      readonly id: number;
      readonly replaced: boolean;
      /**
       * True when this client id had already been stored and nothing changed.
       * A retry is not a second reading, and the caller that marks a scan as
       * corrected must not mark a second one: on a retry the scan marked the
       * first time no longer reads `answered`, so a second lookup finds the
       * device's PREVIOUS scan of the same product and corrupts it.
       */
      readonly alreadyStored: boolean;
    }
  | { readonly ok: false; readonly why: string };

/**
 * Writes one correction, replacing this device's earlier reading of the same
 * subject at the same shop on the same day.
 *
 * Returns why it refused rather than throwing, so the route can answer a phone
 * with a sentence instead of a 500. Every refusal here is a fact about the
 * input, and every drop is counted on the store.
 */
export function recordCorrection(input: CorrectionInput): RecordResult {
  const s = store();
  if (s.db === null) {
    s.dropped += 1;
    return { ok: false, why: s.droppedWhy || 'the corrections store is not open' };
  }

  const subject = subjectOf(input);
  if (subject === null) {
    return { ok: false, why: 'a correction needs a barcode, a product, or the text that was on screen' };
  }

  const seller = input.seller.trim();
  if (seller === '') return { ok: false, why: 'a correction needs the shop it was seen in' };
  if (seller.toLowerCase() === NOT_A_SELLER) {
    return { ok: false, why: `"${NOT_A_SELLER}" is what the engine says when no shop was named, not a shop` };
  }
  if (!Number.isInteger(input.priceCents) || input.priceCents <= 0) {
    return { ok: false, why: 'a price is a whole number of cents above zero' };
  }
  if (!/^\d{4}-\d{2}-\d{2}$/.test(input.seenOn)) {
    return { ok: false, why: 'the date a tag was seen is an ISO date, no time' };
  }

  const code = input.code && input.code.trim() !== '' ? padGtin(input.code.trim()) : null;
  const productId = input.productId && input.productId.trim() !== '' ? input.productId.trim() : null;
  const key = sellerKey(seller);
  const now = new Date().toISOString();

  try {
    /*
     * A retry, not a second reading. The phone re-sends anything it has no
     * acknowledgement for, so an id it has already stored must change nothing
     * and still report success, or the queue re-sends it forever.
     */
    const seen = s.db
      .prepare('SELECT id FROM correction WHERE client_id = ?')
      .get(input.clientId) as { id: number } | undefined;
    if (seen) return { ok: true, id: seen.id, replaced: false, alreadyStored: true };

    /*
     * THE SAME SHELF, READ TWICE BY ONE PERSON, and the reason this lookup is
     * three conditions rather than one unique index.
     *
     * A correction is filed under its most specific key: a barcode if there was
     * one, otherwise the product key, otherwise the text. But the same product
     * arrives under different keys on different days depending on how it was
     * found: scanned once, searched by name the next time. Matching only on the
     * filed key would let one person file a scan row and a text row for one
     * shelf on one day, and the spine would read them as two witnesses
     * agreeing. That is the exact thing the whole store exists to prevent, and
     * a unique index on any single column cannot see it.
     *
     * So the match is: same device, same shop, same day, and ANY key in common,
     * including the label. The label is in there as the last resort and it
     * earns its place: two readings can genuinely share no identifier at all
     * (one filed from a bare barcode, one from a bare text search), and the
     * only thing left tying them together is that the person was looking at the
     * same words both times. The unique index stays as a backstop for the filed
     * key.
     */
    const labelKey = (input.label ?? '').trim().toLowerCase().replace(/\s+/g, ' ') || null;
    const existing = s.db
      .prepare(
        `SELECT id FROM correction
          WHERE device_id = ? AND seller_key = ? AND seen_on = ?
            AND (subject = ?
                 OR (? IS NOT NULL AND code = ?)
                 OR (? IS NOT NULL AND product_id = ?)
                 OR (? IS NOT NULL AND lower(trim(label)) = ?))
          LIMIT 1`,
      )
      .get(
        input.deviceId,
        key,
        input.seenOn,
        subject,
        code,
        code,
        productId,
        productId,
        labelKey,
        labelKey,
      ) as { id: number } | undefined;

    if (existing) {
      // The newer reading of the same tag replaces the older one. Any key this
      // reading carries that the stored row was missing is filled in, so a row
      // first filed from a text search becomes findable by barcode once the
      // same person scans it.
      s.db
        .prepare(
          `UPDATE correction SET
             client_id   = ?,
             price_cents = ?,
             kind        = ?,
             label       = COALESCE(?, label),
             category    = COALESCE(?, category),
             code        = COALESCE(code, ?),
             product_id  = COALESCE(product_id, ?),
             seller      = ?,
             recorded_at = ?
           WHERE id = ?`,
        )
        .run(
          input.clientId,
          input.priceCents,
          input.kind,
          input.label,
          input.category,
          code,
          productId,
          seller,
          now,
          existing.id,
        );
      return { ok: true, id: existing.id, replaced: true, alreadyStored: false };
    }

    /*
     * THE RATE LIMIT, item 15c, and it is checked HERE rather than at the top of
     * this function on purpose. A retry returns above this line and a second
     * reading of a shelf this device already filed today is an UPDATE, not a new
     * row; neither is a new price, so neither may be refused by a cap on new
     * prices. Counting them would mean a phone that fixes its own typo twice
     * loses two of its day's readings, and a flaky aisle that re-sends would
     * spend the whole cap on one number.
     */
    const filedToday = s.db
      .prepare('SELECT COUNT(*) AS n FROM correction WHERE device_id = ? AND substr(recorded_at, 1, 10) = ?')
      .get(input.deviceId, now.slice(0, 10)) as { n: number } | undefined;
    if ((filedToday?.n ?? 0) >= TYPED_PRICES_PER_DEVICE_PER_DAY) {
      return {
        ok: false,
        why: `this phone has already sent ${TYPED_PRICES_PER_DEVICE_PER_DAY} prices today, which is as many as one day's readings count for. Tomorrow's count again.`,
      };
    }

    const row = s.db
      .prepare(
        `INSERT INTO correction
           (client_id, device_id, subject, code, product_id, label, category,
            seller, seller_key, price_cents, kind, seen_on, recorded_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
         RETURNING id`,
      )
      .get(
        input.clientId,
        input.deviceId,
        subject,
        code,
        productId,
        input.label,
        input.category,
        seller,
        key,
        input.priceCents,
        input.kind,
        input.seenOn,
        now,
      ) as { id: number } | undefined;

    if (row === undefined) {
      s.dropped += 1;
      s.droppedWhy = 'insert returned no row';
      return { ok: false, why: 'the correction did not store' };
    }
    return { ok: true, id: row.id, replaced: false, alreadyStored: false };
  } catch (err) {
    s.dropped += 1;
    s.droppedWhy = err instanceof Error ? err.message : String(err);
    return { ok: false, why: s.droppedWhy };
  }
}

/**
 * Every correction filed against a product, newest first.
 *
 * Both keys are asked for, not one: a correction typed against a barcode and a
 * correction typed against the same product resolved from text are the same
 * shelf and must both come back, or a person who scanned and a person who typed
 * are kept in separate worlds and neither ever reaches two points.
 *
 * Reads never throw and an unopened store is an empty list, so a missing
 * corrections file makes the app behave exactly as it did before this feature
 * existed rather than failing a verdict.
 */
export function correctionsFor(input: {
  code?: string | null;
  productId?: string | null;
}): CorrectionRow[] {
  const s = store();
  if (s.db === null) return [];
  const code = input.code && input.code.trim() !== '' ? padGtin(input.code.trim()) : null;
  const productId = input.productId && input.productId.trim() !== '' ? input.productId.trim() : null;
  if (code === null && productId === null) return [];
  try {
    /*
     * Either key finds the row, never only the one it was filed under. A
     * correction typed after a barcode scan and a correction typed after a name
     * search are the same shelf, and matching only on the filed key would keep
     * the people who scan and the people who type in separate worlds where
     * neither ever reaches the two points a verdict needs.
     */
    return s.db
      .prepare(
        `SELECT * FROM correction
          WHERE (? IS NOT NULL AND (code = ? OR subject = ?))
             OR (? IS NOT NULL AND (product_id = ? OR subject = ?))
          ORDER BY seen_on DESC, id DESC`,
      )
      .all(
        code,
        code,
        code === null ? null : `gtin:${code}`,
        productId,
        productId,
        productId === null ? null : `pid:${productId}`,
      ) as unknown as CorrectionRow[];
  } catch (err) {
    s.dropped += 1;
    s.droppedWhy = err instanceof Error ? err.message : String(err);
    return [];
  }
}

/**
 * How many independent people have reported the same shelf at the same shop.
 *
 * D-022. The unique index upstream stops one device manufacturing agreement
 * with itself, and until now that was the whole integrity story: two devices
 * reporting the same wrong number were indistinguishable from two honest
 * shoppers, and one device reporting one number moved a verdict on its own.
 * The index cannot fix that, because it is doing a different job.
 *
 * A row is corroborated when a **different device** reported the same subject
 * at the same shop for a price close enough to be the same tag. Close enough is
 * deliberately generous: shelf tags move, someone reads $3.99 the day before a
 * sale ends and someone else reads $4.49 the day after, and calling those two
 * different observations would make corroboration almost unreachable and the
 * mechanism decorative. What it must not do is let two genuinely different
 * numbers vouch for each other, which is what the ceiling is for.
 *
 * Returned as a count and not a boolean because the spine weighs it: one
 * witness is a claim, two is a reading, and the difference decides whether an
 * outlier is published or held.
 *
 * NOT a reliability score per person, which D-022 also asks for and which this
 * is not. That needs a history of a device being contradicted, which needs
 * volume this app does not have. Named here so the gap stays visible.
 */
export const CORROBORATION_TOLERANCE = 0.12;
export const CORROBORATION_FLOOR_CENTS = 25;

export function witnessesFor(rows: readonly CorrectionRow[]): Map<number, number> {
  const out = new Map<number, number>();
  for (const row of rows) {
    const near = rows.filter((other) => {
      if (other.id === row.id) return false;
      // A second reading from the same phone is the same witness, not a second
      // one. This is the whole point: it is what the unique index cannot say,
      // because that index is per day and a person can come back tomorrow.
      if (other.device_id === row.device_id) return false;
      if (sellerKey(other.seller) !== sellerKey(row.seller)) return false;
      const gap = Math.abs(other.price_cents - row.price_cents);
      const allowed = Math.max(CORROBORATION_FLOOR_CENTS, row.price_cents * CORROBORATION_TOLERANCE);
      return gap <= allowed;
    });
    out.set(row.id, 1 + new Set(near.map((n) => n.device_id)).size);
  }
  return out;
}

/**
 * What one phone's reporting history is worth, item 15c.
 *
 * A report is corroborated under exactly the rule `witnessesFor` above uses, and
 * the SQL below is that rule and not a second version of it: same shop, same
 * subject, a different device, and a price inside the same band. Written as one
 * statement rather than by re-reading every row through `witnessesFor` because
 * this question is asked about a device across every product it ever reported,
 * where that one is asked about one product across its reporters.
 *
 * `score` starts at zero for a phone that has never been confirmed by anybody
 * and reaches one at `RELIABILITY_FULL_AT` confirmed readings. Read the constant
 * for what this does and does not gate.
 */
export interface ReporterReliability {
  readonly deviceId: string;
  /** Every reading this phone has filed. */
  readonly reports: number;
  /** The ones another phone has since agreed with, on the same shelf, inside the band. */
  readonly corroborated: number;
  /** 0 to 1. Zero until somebody else sees the same tag. */
  readonly score: number;
}

const CORROBORATED_BY_OTHERS = `
  SELECT c.device_id AS device_id,
         COUNT(*) AS reports,
         SUM(
           CASE WHEN EXISTS (
             SELECT 1 FROM correction o
              WHERE o.subject = c.subject
                AND o.seller_key = c.seller_key
                AND o.device_id <> c.device_id
                AND abs(o.price_cents - c.price_cents) <= max(?, c.price_cents * ?)
           ) THEN 1 ELSE 0 END
         ) AS corroborated
    FROM correction c`;

function reliabilityRows(s: CorrectionStore, deviceId: string | null): ReporterReliability[] {
  if (s.db === null) return [];
  try {
    const sql = `${CORROBORATED_BY_OTHERS}${deviceId === null ? '' : ' WHERE c.device_id = ?'} GROUP BY c.device_id ORDER BY c.device_id`;
    const args: (string | number)[] = [CORROBORATION_FLOOR_CENTS, CORROBORATION_TOLERANCE];
    if (deviceId !== null) args.push(deviceId);
    const rows = s.db.prepare(sql).all(...args) as unknown as {
      device_id: string;
      reports: number;
      corroborated: number;
    }[];
    return rows.map((r) => ({
      deviceId: r.device_id,
      reports: r.reports,
      corroborated: r.corroborated,
      score: Math.min(1, r.corroborated / RELIABILITY_FULL_AT),
    }));
  } catch (err) {
    s.dropped += 1;
    s.droppedWhy = err instanceof Error ? err.message : String(err);
    return [];
  }
}

/**
 * One phone's score. A phone that has never filed anything is zero of zero
 * rather than an absence: it has reported nothing and been confirmed on nothing,
 * which is exactly what the numbers say, and a caller that had to tell "no rows"
 * from "no corroboration" would get it wrong the first time.
 */
export function reliabilityOf(deviceId: string, s: CorrectionStore = store()): ReporterReliability {
  const rows = reliabilityRows(s, deviceId);
  return rows[0] ?? { deviceId, reports: 0, corroborated: 0, score: 0 };
}

/** Every phone that has ever filed a price, for a report. Never shown to a shopper. */
export function reporterReliability(s: CorrectionStore = store()): ReporterReliability[] {
  return reliabilityRows(s, null);
}

/** How many new prices this phone may still file today. Item 15c, for a route that wants to say so early. */
export function typedPricesLeftToday(
  deviceId: string,
  now: Date = new Date(),
  s: CorrectionStore = store(),
): number {
  if (s.db === null) return 0;
  try {
    const row = s.db
      .prepare('SELECT COUNT(*) AS n FROM correction WHERE device_id = ? AND substr(recorded_at, 1, 10) = ?')
      .get(deviceId, now.toISOString().slice(0, 10)) as { n: number } | undefined;
    return Math.max(0, TYPED_PRICES_PER_DEVICE_PER_DAY - (row?.n ?? 0));
  } catch {
    return 0;
  }
}

/** Every row, for tests and for the one-line count a report prints. */
export function allCorrections(s: CorrectionStore = store()): CorrectionRow[] {
  if (s.db === null) return [];
  try {
    return s.db.prepare('SELECT * FROM correction ORDER BY id').all() as unknown as CorrectionRow[];
  } catch {
    return [];
  }
}
