/**
 * Prices people typed in themselves, and the only place they live.
 *
 * Until this file existed, a correction was collected and applied to nothing:
 * `app/public/js/store.js` said so in its own comment on the `corrections`
 * field, and the mascot line that goes with it ("counts once a second tag
 * agrees") described a mechanism that was not built. This table is that
 * mechanism. A correction written here is read back by
 * `spine/src/sources/corrections.ts` as an ordinary price point, so the next
 * verdict for the same product is computed with it in the comparison set.
 *
 * SEPARATE FILE, not a table inside prices.db, for the reason `store.ts` gives
 * for keeping observations out of the catalogue: these two tables have
 * different owners and different lifetimes. `observation` is written by a
 * crawler and can be rebuilt from a re-crawl. A correction cannot be rebuilt by
 * anything: it is one person's eyes on one shelf on one day, and if it is lost
 * it is lost. It gets a file nothing else rewrites.
 *
 * ONE PERSON, ONE SHOP, ONE DAY, ONE PRICE. The unique index is the whole
 * integrity story. Grocery needs two price points to produce a verdict
 * (`spine/src/categories.ts`, minPoints 2), so without that index a person who
 * taps save twice manufactures the agreement the product is supposed to wait
 * for, and the app would tell them their own number is confirmed. A repeat for
 * the same subject, shop and day overwrites: the newest reading of the same tag
 * is a correction of the earlier one, never a second witness to it.
 *
 * WHAT IS NOT HERE. No name, no email, no account, no location. `device_id` is
 * the random UUID the client generates on first run (`app/public/js/device.js`)
 * and it identifies a phone's local storage, never a person, exactly as
 * `app/src/scans.ts` documents for the same field. `seller` is what the person
 * typed, because a price with no shop cannot be excluded from its own
 * comparison later, and the spine's self-exclusion keys on that string.
 *
 * NEVER THROWS. Same contract as `app/src/scans.ts`: a store that could not be
 * opened is a `db: null` handle whose writes are counted in `dropped`, not an
 * exception thrown at a request handler. A phone correcting a price must never
 * be able to take the server down.
 */

import { DatabaseSync } from 'node:sqlite';
import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Resolved once and exported, the same way `store.ts` exports `PRICES_DB_PATH`,
 * so the writer (`app/server.ts`) and the reader (the spine source) agree on
 * where the file is without either hardcoding a path into the other's package.
 */
export const CORRECTIONS_DB_PATH =
  process.env.SHIN_CORRECTIONS ?? fileURLToPath(new URL('../data/corrections.db', import.meta.url));

/**
 * Whether the number is what the thing normally costs or what it costs today.
 * The same two values `price/src/store.ts` uses, and the reason the correction
 * screen asks at all: `spine/src/contract.ts` calls collapsing these "the single
 * most expensive mistake available here", and a shopper reading a sale tag into
 * a field labelled regular walks the everyday price down for everyone.
 */
export type CorrectionKind = 'regular' | 'promotional';

export interface CorrectionInput {
  /**
   * Generated by the client, unique per correction, and the reason a phone with
   * no signal can retry safely. The queue in `app/public/js/store.js` re-sends
   * anything it has not seen an acknowledgement for, and without this a flaky
   * aisle turns one price into three witnesses.
   */
  readonly clientId: string;
  readonly deviceId: string;
  /** Barcode, zero padded to 13 by `recordCorrection`. Null when the scan produced none. */
  readonly code: string | null;
  /** The spine's own identity key, when a verdict had one. Null on a refusal with no identity. */
  readonly productId: string | null;
  /** What was on screen when they corrected it. Display only, never a join key. */
  readonly label: string | null;
  readonly category: string | null;
  readonly seller: string;
  readonly priceCents: number;
  readonly kind: CorrectionKind;
  /** ISO date, no time. A tag is a fact about a day. */
  readonly seenOn: string;
}

export interface CorrectionRow {
  readonly id: number;
  readonly client_id: string;
  readonly device_id: string;
  readonly subject: string;
  readonly code: string | null;
  readonly product_id: string | null;
  readonly label: string | null;
  readonly category: string | null;
  readonly seller: string;
  readonly price_cents: number;
  readonly kind: CorrectionKind;
  readonly seen_on: string;
  readonly recorded_at: string;
}

const DDL = `
CREATE TABLE IF NOT EXISTS correction (
  id          INTEGER PRIMARY KEY,
  client_id   TEXT NOT NULL UNIQUE,
  device_id   TEXT NOT NULL,
  subject     TEXT NOT NULL,
  code        TEXT,
  product_id  TEXT,
  label       TEXT,
  category    TEXT,
  seller      TEXT NOT NULL,
  seller_key  TEXT NOT NULL,
  price_cents INTEGER NOT NULL,
  kind        TEXT NOT NULL CHECK (kind IN ('regular', 'promotional')),
  seen_on     TEXT NOT NULL,
  recorded_at TEXT NOT NULL
) STRICT;

CREATE UNIQUE INDEX IF NOT EXISTS correction_one_per_shop_per_day
  ON correction(device_id, subject, seller_key, seen_on);

CREATE INDEX IF NOT EXISTS correction_subject ON correction(subject, seen_on);
CREATE INDEX IF NOT EXISTS correction_code ON correction(code);
CREATE INDEX IF NOT EXISTS correction_product ON correction(product_id);
CREATE INDEX IF NOT EXISTS correction_dedupe ON correction(device_id, seller_key, seen_on);
`;

export interface CorrectionStore {
  readonly path: string;
  readonly db: DatabaseSync | null;
  /** Writes or reads that could not complete since this handle was opened. */
  dropped: number;
  /** Why the last drop happened. Empty string when nothing has dropped. */
  droppedWhy: string;
}

let active: CorrectionStore | null = null;

/** The store currently in use, or null if nothing has opened one yet. */
export function activeCorrectionStore(): CorrectionStore | null {
  return active;
}

/**
 * Opens (creating if needed) the corrections database and makes it the target
 * of future calls. Never throws: a path that cannot be created comes back as a
 * handle with `db: null` and `droppedWhy` set.
 */
export function openCorrectionStore(path: string = CORRECTIONS_DB_PATH): CorrectionStore {
  let db: DatabaseSync | null = null;
  let droppedWhy = '';
  try {
    if (path !== ':memory:') mkdirSync(dirname(path), { recursive: true });
    db = new DatabaseSync(path);
    db.exec('PRAGMA journal_mode = WAL');
    db.exec(DDL);
  } catch (err) {
    db = null;
    droppedWhy = err instanceof Error ? err.message : String(err);
  }
  const store: CorrectionStore = { path, db, dropped: 0, droppedWhy };
  active = store;
  return store;
}

function store(): CorrectionStore {
  return active ?? openCorrectionStore();
}

export function padGtin(gtin: string): string {
  return gtin.padStart(13, '0');
}

/**
 * The key a correction is filed under and looked up by, in priority order:
 * a barcode if there was one, then the spine's identity key, then the text the
 * person was looking at.
 *
 * The prefixes are not decoration. Without them a product id that happened to
 * be all digits would collide with a barcode, and a typed label would collide
 * with either, which is the quiet kind of wrong that shows a shopper someone
 * else's price for a different thing.
 */
export function subjectOf(input: {
  code: string | null;
  productId: string | null;
  label: string | null;
}): string | null {
  if (input.code && input.code.trim() !== '') return `gtin:${padGtin(input.code.trim())}`;
  if (input.productId && input.productId.trim() !== '') return `pid:${input.productId.trim()}`;
  const label = (input.label ?? '').trim().toLowerCase().replace(/\s+/g, ' ');
  return label === '' ? null : `text:${label}`;
}

/**
 * The self-exclusion key. Deliberately the same shape as
 * `spine/src/sources/source.ts`'s `normalizeSeller`, duplicated rather than
 * imported because this package must not depend on the spine (the spine already
 * depends on this direction, via the source adapter). If those two ever
 * disagree, a correction from the shop a shopper is standing in stops being
 * excluded from its own comparison, so the shared test in
 * `price/test/corrections.test.ts` asserts they agree on the cases that matter.
 */
const SELLER_NOISE = /\b(inc|ltd|ltee|limited|corp|corporation|co|canada|ca|com|banners|stores|store)\b/g;

const COMBINING_LOW = 0x0300;
const COMBINING_HIGH = 0x036f;

export function sellerKey(seller: string): string {
  // Folded by code point rather than by a literal character class, for the
  // reason source.ts gives: the rule stays readable in a diff, and a range of
  // invisible combining marks pasted into a regex is a thing nobody can review.
  let folded = '';
  for (const ch of seller.normalize('NFD')) {
    const code = ch.codePointAt(0) ?? 0;
    if (code >= COMBINING_LOW && code <= COMBINING_HIGH) continue;
    folded += ch;
  }
  const base = folded
    .toLowerCase()
    .replace(/[^a-z0-9\s.]/g, ' ')
    .replace(/\./g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
  const stripped = base.replace(SELLER_NOISE, ' ').trim();
  const kept = stripped.length > 0 ? stripped : base;
  return kept.replace(/\s+/g, '');
}

/** The literal string the spine uses when no shop was named. Never a seller, so never stored as one. */
const NOT_A_SELLER = 'given';

export type RecordResult =
  | { readonly ok: true; readonly id: number; readonly replaced: boolean }
  | { readonly ok: false; readonly why: string };

/**
 * Writes one correction, replacing this device's earlier reading of the same
 * subject at the same shop on the same day.
 *
 * Returns why it refused rather than throwing, so the route can answer a phone
 * with a sentence instead of a 500. Every refusal here is a fact about the
 * input, and every drop is counted on the store.
 */
export function recordCorrection(input: CorrectionInput): RecordResult {
  const s = store();
  if (s.db === null) {
    s.dropped += 1;
    return { ok: false, why: s.droppedWhy || 'the corrections store is not open' };
  }

  const subject = subjectOf(input);
  if (subject === null) {
    return { ok: false, why: 'a correction needs a barcode, a product, or the text that was on screen' };
  }

  const seller = input.seller.trim();
  if (seller === '') return { ok: false, why: 'a correction needs the shop it was seen in' };
  if (seller.toLowerCase() === NOT_A_SELLER) {
    return { ok: false, why: `"${NOT_A_SELLER}" is what the engine says when no shop was named, not a shop` };
  }
  if (!Number.isInteger(input.priceCents) || input.priceCents <= 0) {
    return { ok: false, why: 'a price is a whole number of cents above zero' };
  }
  if (!/^\d{4}-\d{2}-\d{2}$/.test(input.seenOn)) {
    return { ok: false, why: 'the date a tag was seen is an ISO date, no time' };
  }

  const code = input.code && input.code.trim() !== '' ? padGtin(input.code.trim()) : null;
  const productId = input.productId && input.productId.trim() !== '' ? input.productId.trim() : null;
  const key = sellerKey(seller);
  const now = new Date().toISOString();

  try {
    /*
     * A retry, not a second reading. The phone re-sends anything it has no
     * acknowledgement for, so an id it has already stored must change nothing
     * and still report success, or the queue re-sends it forever.
     */
    const seen = s.db
      .prepare('SELECT id FROM correction WHERE client_id = ?')
      .get(input.clientId) as { id: number } | undefined;
    if (seen) return { ok: true, id: seen.id, replaced: false };

    /*
     * THE SAME SHELF, READ TWICE BY ONE PERSON, and the reason this lookup is
     * three conditions rather than one unique index.
     *
     * A correction is filed under its most specific key: a barcode if there was
     * one, otherwise the product key, otherwise the text. But the same product
     * arrives under different keys on different days depending on how it was
     * found: scanned once, searched by name the next time. Matching only on the
     * filed key would let one person file a scan row and a text row for one
     * shelf on one day, and the spine would read them as two witnesses
     * agreeing. That is the exact thing the whole store exists to prevent, and
     * a unique index on any single column cannot see it.
     *
     * So the match is: same device, same shop, same day, and ANY key in common,
     * including the label. The label is in there as the last resort and it
     * earns its place: two readings can genuinely share no identifier at all
     * (one filed from a bare barcode, one from a bare text search), and the
     * only thing left tying them together is that the person was looking at the
     * same words both times. The unique index stays as a backstop for the filed
     * key.
     */
    const labelKey = (input.label ?? '').trim().toLowerCase().replace(/\s+/g, ' ') || null;
    const existing = s.db
      .prepare(
        `SELECT id FROM correction
          WHERE device_id = ? AND seller_key = ? AND seen_on = ?
            AND (subject = ?
                 OR (? IS NOT NULL AND code = ?)
                 OR (? IS NOT NULL AND product_id = ?)
                 OR (? IS NOT NULL AND lower(trim(label)) = ?))
          LIMIT 1`,
      )
      .get(
        input.deviceId,
        key,
        input.seenOn,
        subject,
        code,
        code,
        productId,
        productId,
        labelKey,
        labelKey,
      ) as { id: number } | undefined;

    if (existing) {
      // The newer reading of the same tag replaces the older one. Any key this
      // reading carries that the stored row was missing is filled in, so a row
      // first filed from a text search becomes findable by barcode once the
      // same person scans it.
      s.db
        .prepare(
          `UPDATE correction SET
             client_id   = ?,
             price_cents = ?,
             kind        = ?,
             label       = COALESCE(?, label),
             category    = COALESCE(?, category),
             code        = COALESCE(code, ?),
             product_id  = COALESCE(product_id, ?),
             seller      = ?,
             recorded_at = ?
           WHERE id = ?`,
        )
        .run(
          input.clientId,
          input.priceCents,
          input.kind,
          input.label,
          input.category,
          code,
          productId,
          seller,
          now,
          existing.id,
        );
      return { ok: true, id: existing.id, replaced: true };
    }

    const row = s.db
      .prepare(
        `INSERT INTO correction
           (client_id, device_id, subject, code, product_id, label, category,
            seller, seller_key, price_cents, kind, seen_on, recorded_at)
         VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
         RETURNING id`,
      )
      .get(
        input.clientId,
        input.deviceId,
        subject,
        code,
        productId,
        input.label,
        input.category,
        seller,
        key,
        input.priceCents,
        input.kind,
        input.seenOn,
        now,
      ) as { id: number } | undefined;

    if (row === undefined) {
      s.dropped += 1;
      s.droppedWhy = 'insert returned no row';
      return { ok: false, why: 'the correction did not store' };
    }
    return { ok: true, id: row.id, replaced: false };
  } catch (err) {
    s.dropped += 1;
    s.droppedWhy = err instanceof Error ? err.message : String(err);
    return { ok: false, why: s.droppedWhy };
  }
}

/**
 * Every correction filed against a product, newest first.
 *
 * Both keys are asked for, not one: a correction typed against a barcode and a
 * correction typed against the same product resolved from text are the same
 * shelf and must both come back, or a person who scanned and a person who typed
 * are kept in separate worlds and neither ever reaches two points.
 *
 * Reads never throw and an unopened store is an empty list, so a missing
 * corrections file makes the app behave exactly as it did before this feature
 * existed rather than failing a verdict.
 */
export function correctionsFor(input: {
  code?: string | null;
  productId?: string | null;
}): CorrectionRow[] {
  const s = store();
  if (s.db === null) return [];
  const code = input.code && input.code.trim() !== '' ? padGtin(input.code.trim()) : null;
  const productId = input.productId && input.productId.trim() !== '' ? input.productId.trim() : null;
  if (code === null && productId === null) return [];
  try {
    /*
     * Either key finds the row, never only the one it was filed under. A
     * correction typed after a barcode scan and a correction typed after a name
     * search are the same shelf, and matching only on the filed key would keep
     * the people who scan and the people who type in separate worlds where
     * neither ever reaches the two points a verdict needs.
     */
    return s.db
      .prepare(
        `SELECT * FROM correction
          WHERE (? IS NOT NULL AND (code = ? OR subject = ?))
             OR (? IS NOT NULL AND (product_id = ? OR subject = ?))
          ORDER BY seen_on DESC, id DESC`,
      )
      .all(
        code,
        code,
        code === null ? null : `gtin:${code}`,
        productId,
        productId,
        productId === null ? null : `pid:${productId}`,
      ) as unknown as CorrectionRow[];
  } catch (err) {
    s.dropped += 1;
    s.droppedWhy = err instanceof Error ? err.message : String(err);
    return [];
  }
}

/** Every row, for tests and for the one-line count a report prints. */
export function allCorrections(s: CorrectionStore = store()): CorrectionRow[] {
  if (s.db === null) return [];
  try {
    return s.db.prepare('SELECT * FROM correction ORDER BY id').all() as unknown as CorrectionRow[];
  } catch {
    return [];
  }
}
