/**
 * public/icon-180.png, from public/icon.svg.
 *
 * iOS ignores an SVG `apple-touch-icon` and substitutes a screenshot of the
 * page, which for a camera-first app on a dark ground is a black square. So the
 * home screen needs a raster, and a raster generated by hand is a raster that
 * drifts from the vector it came from -- which is the same failure the share
 * card had with its colour tokens, one file type over.
 *
 * No image dependency. This drives the headless Chrome that is already on the
 * machine, the same way scripts/fonts.mjs reaches for the network and
 * scripts/build-faces.mjs reaches for the face module: the tool exists, so the
 * script uses it rather than the repo growing a rasteriser.
 *
 * The SVG is 512x512 with explicit width and height, so a 180x180 window clips
 * it rather than scaling it -- the first attempt at this produced the top-left
 * corner of the icon and looked plausible at a glance. It is loaded through a
 * throwaway page that sizes it instead.
 *
 *   node scripts/build-icon.mjs              rewrite the PNG
 *   node scripts/build-icon.mjs --check      fail if it has drifted
 */

import { execFileSync } from 'node:child_process';
import { existsSync, mkdtempSync, readFileSync, rmSync, writeFileSync, copyFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

const PUBLIC = fileURLToPath(new URL('../public/', import.meta.url));
const SVG = join(PUBLIC, 'icon.svg');
const PNG = join(PUBLIC, 'icon-180.png');
export const SIZE = 180;

/**
 * Where a headless Chrome lives. CHROME_PATH first, so a machine that keeps it
 * somewhere else can say so without editing this file.
 */
const CANDIDATES = [
  process.env.CHROME_PATH,
  'C:/Program Files/Google/Chrome/Application/chrome.exe',
  'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe',
  'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',
  '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
  '/usr/bin/google-chrome',
  '/usr/bin/chromium',
].filter(Boolean);

function findBrowser() {
  return CANDIDATES.find((p) => existsSync(p)) ?? null;
}

/** Render icon.svg at SIZE and return the PNG bytes. */
function renderIcon() {
  const browser = findBrowser();
  if (!browser) {
    throw new Error(
      `no headless browser found. Set CHROME_PATH, or install Chrome. Tried:\n  ${CANDIDATES.join('\n  ')}`,
    );
  }
  const dir = mkdtempSync(join(tmpdir(), 'shin-icon-'));
  try {
    // The SVG is copied in beside the page so the page can reference it with a
    // relative path: a file:// document loading a file:// sibling is allowed,
    // while reaching back out to an absolute path is not, on every platform.
    copyFileSync(SVG, join(dir, 'icon.svg'));
    const page = join(dir, 'shot.html');
    writeFileSync(page, [
      '<!doctype html><meta charset="utf-8">',
      '<style>',
      '  html,body{margin:0;padding:0;background:#0B0C0E;overflow:hidden}',
      `  img{display:block;width:${SIZE}px;height:${SIZE}px}`,
      '</style>',
      `<img src="icon.svg" width="${SIZE}" height="${SIZE}" alt="">`,
    ].join('\n'));

    const out = join(dir, 'out.png');
    execFileSync(browser, [
      '--headless',
      '--disable-gpu',
      // Without this the machine's display scale is baked in and a 180 becomes
      // a 225 on a 125% screen, which is how this repo has been bitten before.
      '--force-device-scale-factor=1',
      '--hide-scrollbars',
      `--screenshot=${out}`,
      `--window-size=${SIZE},${SIZE}`,
      `file:///${page.replace(/\\/g, '/')}`,
    ], { stdio: 'pipe' });

    const bytes = readFileSync(out);
    const problem = pngProblems(bytes);
    if (problem) throw new Error(`the render is not a usable icon: ${problem}`);
    return bytes;
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

/**
 * What a usable icon has to be, read straight out of the PNG header. Catches
 * the failure that actually happened: a render that succeeds and writes a file
 * which is the wrong size, or is one flat colour because the SVG did not parse.
 */
export function pngProblems(bytes) {
  const sig = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];
  if (bytes.length < 33) return 'shorter than a PNG header';
  for (let i = 0; i < sig.length; i++) if (bytes[i] !== sig[i]) return 'not a PNG';
  const width = bytes.readUInt32BE(16);
  const height = bytes.readUInt32BE(20);
  if (width !== SIZE || height !== SIZE) return `${width}x${height}, wanted ${SIZE}x${SIZE}`;
  // A clipped or unparsed icon compresses to almost nothing. The real one is
  // ~13 kB; the corner-only render that clipping produced was 3.2 kB.
  if (bytes.length < 6000) return `only ${bytes.length} bytes, which is a flat or clipped render`;
  return null;
}

const isCheck = process.argv.includes('--check');
if (process.argv[1] && import.meta.url.endsWith(process.argv[1].replace(/\\/g, '/').split('/').pop())) {
  if (isCheck) {
    if (!existsSync(PNG)) {
      console.error('icon-180.png is missing. Run `npm run icon`.');
      process.exit(1);
    }
    const onDisk = readFileSync(PNG);
    const problem = pngProblems(onDisk);
    if (problem) {
      console.error(`icon-180.png is not usable: ${problem}`);
      process.exit(1);
    }
    console.log(`icon-180.png ok: ${SIZE}x${SIZE}, ${onDisk.length} bytes`);
  } else {
    const bytes = renderIcon();
    writeFileSync(PNG, bytes);
    console.log(`wrote public/icon-180.png, ${SIZE}x${SIZE}, ${bytes.length} bytes`);
  }
}
